# Generated by Django 4.0.5 on 2022-09-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_cutter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='clicks',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='url',
            name='shortened',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(help_text='The URL to be shortened', unique=True),
        ),
    ]
